# Generated by Django 5.2.14 on 2026-08-30 05:32

import brokercity.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment method', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the bank', max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the bank', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_opening', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance of the bank', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('AED', 'UAE Dirham'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal')], default='SAR', help_text='Currency of the account', max_length=3)),
                ('account_number', models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True)),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=34, null=True)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the bank account is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the bank was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the bank was last updated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the bank', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cash box', max_length=100, unique=True)),
                ('balance_opening', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening balance of the cash box', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the cash box', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('AED', 'UAE Dirham'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal')], default='SAR', help_text='Currency of the cash box', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the cash box is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when last updated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the cash box', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the payment method', max_length=100)),
                ('type', models.CharField(choices=[('expenses', 'Expenses'), ('revenues', 'Revenues')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when last updated')),
                ('category', models.ForeignKey(help_text='Categories of account', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='brokercity.accountcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor'), ('prospect', 'Prospect')], default='user', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(default=brokercity.models.generate_default_transaction_no, editable=False, help_text='Auto-generated transaction number', max_length=20, unique=True)),
                ('transaction_date', models.DateField(help_text='Date of the transaction')),
                ('type', models.CharField(choices=[('deposit', 'Deposit / Income'), ('withdraw', 'Withdraw / Expense')], help_text='Type of transaction (deposit or withdraw)', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_withdraw', models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('amount_to_arabic', models.CharField(help_text='Amount number to arabic language', max_length=10)),
                ('amount_to_english', models.CharField(help_text='Amount number to arabic language', max_length=10)),
                ('currency', models.CharField(choices=[('AED', 'UAE Dirham'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('SAR', 'Saudi Riyal')], default='AED', help_text='Currency of the transaction', max_length=10)),
                ('payment_method', models.CharField(choices=[('banks', 'Banks'), ('cash', 'Cash')], help_text='Type of payment (banks or cash)', max_length=10)),
                ('has_check', models.BooleanField(default=False, help_text='Check if transaction has a check')),
                ('check_no', models.CharField(blank=True, help_text='Check number', max_length=50, null=True)),
                ('check_bank', models.CharField(blank=True, help_text='Bank name on the check', max_length=100, null=True)),
                ('check_date', models.DateField(blank=True, help_text='Date on the check', null=True)),
                ('statement', models.CharField(help_text='Transaction description or statement', max_length=100)),
                ('person_receipt', models.CharField(blank=True, help_text='Person who received the amount', max_length=100, null=True)),
                ('person_deliver', models.CharField(blank=True, help_text='Person who delivered the amount', max_length=100, null=True)),
                ('user_signature', models.TextField(blank=True, help_text='Signature of the transaction user (base64 encoded)', null=True)),
                ('manager_signature', models.TextField(blank=True, help_text='Signature of the transaction manager (base64 encoded)', null=True)),
                ('second_person_signature', models.TextField(blank=True, help_text='Signature of the person who received the amount (base64 encoded)', null=True)),
                ('has_document', models.BooleanField(default=False, help_text='Check if transaction has a check')),
                ('document', models.ImageField(blank=True, help_text='Upload scanned document or receipt', null=True, upload_to='transactions/documents/')),
                ('document_no', models.CharField(blank=True, help_text='Document or reference number', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the transaction was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the transaction was last updated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the transaction', null=True)),
                ('account_from', models.ForeignKey(blank=True, help_text='Account from (used for Deposit via Banks/Cash)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='brokercity.account')),
                ('account_to', models.ForeignKey(blank=True, help_text='Account to (used for Withdraw via Banks/Cash)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_to', to='brokercity.account')),
                ('bank', models.ForeignKey(blank=True, help_text='Bank used on this transaction (required if payment_method is banks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_bank', to='brokercity.bank')),
                ('cashbox', models.ForeignKey(blank=True, help_text='CashBox used for Cash transactions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='brokercity.cashbox')),
                ('transaction_user', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
