# Generated by Django 5.2.17 on 2026-08-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='From Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To Account'),
        ),
    ]
