# Generated by Django 5.2.17 on 2026-08-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0002_alter_transaction_account_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_arabic',
            field=models.CharField(blank=True, help_text='Amount number to arabic language', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_english',
            field=models.CharField(blank=True, help_text='Amount number to arabic language', max_length=100, null=True),
        ),
    ]
