# Generated by Django 5.2.17 on 2026-08-31 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0003_alter_transaction_amount_to_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deposit amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_arabic',
            field=models.CharField(blank=True, help_text='Amount number to arabic language', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_english',
            field=models.CharField(blank=True, help_text='Amount number to english language', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Withdraw amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='has_document',
            field=models.BooleanField(default=False, help_text='Check if transaction has a document'),
        ),
    ]
