# Generated by Django 5.2.17 on 2026-09-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0004_alter_transaction_amount_deposit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('twilio_sid', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_from',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='From Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_to',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='To Account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_bank',
            field=models.CharField(blank=True, default='', help_text='Bank name on the check', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_date',
            field=models.DateField(blank=True, default='2024-01-01', help_text='Date on the check'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_no',
            field=models.CharField(blank=True, default='', help_text='Check number', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='document_no',
            field=models.CharField(blank=True, default='', help_text='Document or reference number', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='person_deliver',
            field=models.CharField(blank=True, default='', help_text='Person who delivered the amount', max_length=100),
        ),
    ]
