# Generated by Django 5.2.14 on 2026-09-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0005_customer_whatsappmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='document_no',
            field=models.CharField(blank=True, default='', help_text='Document or reference number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_no',
            field=models.CharField(help_text='Manual transaction number', max_length=20, unique=True),
        ),
    ]
