# Generated by Django 5.2.17 on 2026-09-17 07:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0006_alter_transaction_document_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Name of the owner', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Phone number of the owner', max_length=100, null=True, unique=True)),
                ('address', models.CharField(blank=True, db_index=True, help_text='Address of the owner', max_length=255, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Current balance of the owner', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_opening', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Opening balance of the owner', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the owner was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the owner was last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Name of the category', max_length=100, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('building', 'Building'), ('vila', 'Vila')], default='building', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the category was last updated')),
                ('owner', models.ForeignKey(blank=True, help_text='Owner who owns this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_owner', to='brokercity.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Name of unit', max_length=100, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('vila', 'Vila'), ('room', 'Room')], default='apartment', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('occupied', 'Occupied'), ('available', 'Available')], default='occupied', max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Current price of the unit', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('bedrooms', models.IntegerField(blank=True, help_text='Number of bedrooms', null=True)),
                ('bathrooms', models.IntegerField(blank=True, help_text='Number of bathrooms', null=True)),
                ('has_parking', models.BooleanField(blank=True, help_text='Whether the unit has parking', null=True)),
                ('parking', models.IntegerField(blank=True, help_text='Number of parking spaces', null=True)),
                ('furnished', models.BooleanField(blank=True, help_text='Whether the unit is furnished', null=True)),
                ('unfurnished', models.BooleanField(blank=True, help_text='Whether the unit is unfurnished', null=True)),
                ('image_1', models.ImageField(blank=True, help_text='First unit image', null=True, upload_to='units/')),
                ('image_2', models.ImageField(blank=True, help_text='Second unit image', null=True, upload_to='units/')),
                ('image_3', models.ImageField(blank=True, help_text='Third unit image', null=True, upload_to='units/')),
                ('image_4', models.ImageField(blank=True, help_text='Fourth unit image', null=True, upload_to='units/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the unit was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the unit was last updated')),
                ('category', models.ForeignKey(blank=True, help_text='Category of unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_category', to='brokercity.category')),
            ],
        ),
    ]
