# Generated by Django 5.2.17 on 2026-09-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0007_owner_category_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_owner', to='brokercity.owner'),
        ),
    ]
