# Generated by Django 5.2.17 on 2026-09-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0008_unit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='area',
            field=models.CharField(blank=True, db_index=True, help_text='Area of unit', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='location',
            field=models.CharField(blank=True, db_index=True, help_text='Location of unit', max_length=100, null=True, unique=True),
        ),
    ]
