# Generated by Django 5.2.17 on 2026-09-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0009_unit_area_unit_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='location',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='owner',
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.CharField(blank=True, db_index=True, help_text='Area of unit', max_length=100, null=True),
        ),
    ]
