# Generated by Django 5.2.17 on 2026-09-18 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0010_remove_unit_location_remove_unit_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, help_text='Name of the category', max_length=100, null=True, unique=True)),
                ('type', models.CharField(blank=True, choices=[('building', 'Building'), ('vila', 'Vila')], default='building', max_length=100, null=True)),
                ('status', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the category was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when the category was last updated')),
                ('owner', models.ForeignKey(blank=True, help_text='Owner who owns this building', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_owner', to='brokercity.owner')),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category of unit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_category', to='brokercity.building'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
