# Generated by Django 5.2.17 on 2026-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0011_building_alter_unit_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Slider description', max_length=100)),
                ('image_1', models.ImageField(blank=True, help_text='First slider image', null=True, upload_to='slider/')),
                ('image_2', models.ImageField(blank=True, help_text='Second slider image', null=True, upload_to='slider/')),
                ('image_3', models.ImageField(blank=True, help_text='Third slider image', null=True, upload_to='slider/')),
                ('image_4', models.ImageField(blank=True, help_text='Fourth slider image', null=True, upload_to='slider/')),
            ],
        ),
    ]
