# Generated by Django 5.2.17 on 2026-09-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0012_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_4',
        ),
    ]
