# Generated by Django 5.2.17 on 2026-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0013_rename_image_1_slider_image_remove_slider_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='apartments',
            field=models.CharField(help_text='Apartments', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='area_from',
            field=models.CharField(help_text='Area from', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='booking_fee',
            field=models.CharField(help_text='Booking fee', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='developer',
            field=models.CharField(help_text='Developer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='duplexes',
            field=models.CharField(help_text='Duplexes', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='handover',
            field=models.CharField(help_text='Handover', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_1',
            field=models.ImageField(blank=True, help_text='First slider image', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Second slider image', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Third slider image', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Fourth slider image', null=True, upload_to='slider/'),
        ),
        migrations.AddField(
            model_name='slider',
            name='license_number',
            field=models.CharField(help_text='License number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='location',
            field=models.CharField(help_text='Slider location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='name',
            field=models.CharField(help_text='Slider name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='payment_plan',
            field=models.CharField(help_text='Payment plan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='penthouses',
            field=models.CharField(help_text='Penthouses', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='project_number',
            field=models.CharField(help_text='Project number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='starting_price',
            field=models.CharField(help_text='Starting price', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='studios',
            field=models.CharField(help_text='Studios', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='townhouses',
            field=models.CharField(help_text='Townhouses', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(help_text='Slider description', null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, help_text='Main slider image', null=True, upload_to='slider/'),
        ),
    ]
