# Generated by Django 5.2.17 on 2026-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0014_slider_apartments_slider_area_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('forth', 'Forth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eighth', 'Eighth'), ('ninth', 'Ninth'), ('tenth', 'Tenth')], default='first', max_length=100, null=True),
        ),
    ]
