# Generated by Django 5.2.17 on 2026-09-23 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0015_unit_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rental name', max_length=100, null=True)),
                ('nationality', models.CharField(help_text='Rental location', max_length=100, null=True)),
                ('phone_1', models.CharField(help_text='Rental phone number', max_length=100, null=True)),
                ('phone_2', models.CharField(help_text='Rental second phone number', max_length=100, null=True)),
                ('id_number', models.CharField(help_text='Rental phone number', max_length=100, null=True)),
                ('email', models.CharField(help_text='Rental email address', max_length=100, null=True)),
                ('insurance_balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Current balance of the owner', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Current balance of the owner', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
