# Generated by Django 5.2.17 on 2026-09-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0016_rental'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Developer name', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, help_text='Developer phone', max_length=100, null=True)),
                ('type', models.CharField(blank=True, help_text='Developer type', max_length=100, null=True)),
                ('email', models.CharField(blank=True, help_text='Rental email address', max_length=100, null=True)),
            ],
        ),
    ]
