# Generated by Django 5.2.17 on 2026-09-30 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0017_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Transaction amount', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
