# Generated by Django 5.2.17 on 2026-10-01 13:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0018_transaction_subtotal_transaction_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offersale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, help_text='Reference No', max_length=100, null=True)),
                ('date', models.DateField(blank=True, help_text='Offer date', null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient / customer name (Dear X)', max_length=200, null=True)),
                ('project', models.CharField(blank=True, help_text='Project name', max_length=100, null=True)),
                ('unit_no', models.CharField(blank=True, help_text='Unit Number', max_length=100, null=True, unique=True)),
                ('estimated_completion_date', models.CharField(blank=True, help_text='Estimated Date', max_length=100, null=True)),
                ('listing_title', models.CharField(blank=True, help_text='e.g. 6BR Villa for Sale in Saadiyat Lagoons', max_length=200, null=True)),
                ('unit_type', models.CharField(blank=True, help_text='Unit type', max_length=100, null=True)),
                ('unit_model', models.CharField(blank=True, help_text='Unit type', max_length=100, null=True)),
                ('bedrooms', models.CharField(blank=True, help_text='e.g. 6BR Villa', max_length=50, null=True)),
                ('unit_position', models.CharField(blank=True, help_text='e.g. Single row-Corner', max_length=100, null=True)),
                ('unit_grade', models.CharField(blank=True, help_text='e.g. Premium', max_length=50, null=True)),
                ('unit_note', models.CharField(blank=True, help_text='Extra note e.g. Cool', max_length=100, null=True)),
                ('plot_area', models.CharField(blank=True, help_text='Total Area', max_length=100, null=True)),
                ('gross_saleable_area', models.CharField(blank=True, help_text='Total Area', max_length=100, null=True)),
                ('total_area', models.CharField(blank=True, help_text='Total Area', max_length=100, null=True)),
                ('internal_area', models.CharField(blank=True, help_text='Total Area', max_length=100, null=True)),
                ('terrace_area', models.CharField(blank=True, help_text='Total Area', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Property image', null=True, upload_to='offersale/images/')),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL (alternative to upload)', null=True)),
                ('currency', models.CharField(default='AED', help_text='Currency code', max_length=10)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Original / Base Price', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Selling price', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Premium amount', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('noc_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='NOC fee paid by buyer', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('transfer_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Transfer fee (usually 2%)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('agency_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Agency fee (2% + VAT)', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('owner_paid_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total paid by owner to developer', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('buyer_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Total fees and payments to be paid by buyer', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('promotion', models.CharField(blank=True, help_text='Promotion title', max_length=200, null=True)),
                ('waiver', models.CharField(blank=True, help_text='Waiver (AMC)', max_length=100, null=True)),
                ('waiver_second', models.CharField(blank=True, help_text='Waiver (DLP)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installments', models.JSONField(blank=True, default=list, help_text='List of installment objects (inst_no, milestone, percentage, date, amount)')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Base Price', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Final Price', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('adm_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='ADM Fee', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('adm_admin_fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='ADM Admin Fee', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('unit_no', models.ForeignKey(blank=True, db_column='unit_no', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='brokercity.offersale', to_field='unit_no')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'ordering': ['-id'],
            },
        ),
    ]
