# Generated by Django 5.2.17 on 2026-10-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0019_offersale_paymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='Registered',
            field=models.BooleanField(blank=True, help_text='Whether the unit has parking', null=True),
        ),
    ]
