# Generated by Django 5.2.17 on 2026-10-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0020_developer_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_no', models.IntegerField(blank=True, help_text='Lead No', null=True)),
                ('agent', models.CharField(blank=True, help_text='Agent name', max_length=100, null=True)),
                ('agent_lead_no', models.IntegerField(blank=True, help_text='Agent Lead No', null=True)),
                ('agent_contact_duration', models.IntegerField(blank=True, help_text='Agent contact duration', null=True)),
                ('draws', models.FloatField(blank=True, null=True)),
                ('draws_no', models.IntegerField(blank=True, help_text='Draws No', null=True)),
                ('draws_cause', models.CharField(blank=True, help_text='Draws cause', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
