# Generated by Django 5.2.17 on 2026-10-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokercity', '0021_monitoring'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitoring',
            new_name='Monitor',
        ),
    ]
